train_dataset:
  dataset:
    name: paired-image-folders
    args:
      # root_path_1: ./load/div2k/DIV2K_train_LR_bicubic/X2
      # root_path_2: ./load/div2k/DIV2K_train_HR
      root_path_1: ./load/CT/CT_train_LR_bicubic/X2
      root_path_2: ./load/CT/CT_train_HR
      repeat: 20
      cache: none
  wrapper:
    name: sr-implicit-paired
    args:
      inp_size: 48
      augment: true
  batch_size: 16

val_dataset:
  dataset:
    name: paired-image-folders
    args:
      # root_path_1: ./load/div2k/DIV2K_valid_LR_bicubic/X2
      # root_path_2: ./load/div2k/DIV2K_valid_HR
      root_path_1: ./load/CT/CT_valid_LR_bicubic/X2
      root_path_2: ./load/CT/CT_valid_HR
      first_k: 10
      repeat: 160
      cache: none
  wrapper:
    name: sr-implicit-paired
    args:
      inp_size: 48
  batch_size: 16

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: liif
  args:
    encoder_spec:
      name: edsr-baseline
      args:
        scale: 2

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 20
multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

epoch_val: 1
epoch_save: 100

resume: ./save/_train_edsr-baseline-x2/epoch-last.pth