test_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: /content/CT/CT_test_LR_bicubic/X3
      root_path_2: /content/CT/CT_test_HR
  wrapper:
    name: sr-implicit-paired
    args: {}
  batch_size: 1
eval_type: 
eval_bsize: 
scale: 3

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}